---
title: "Models Ensemble"
author: "ernestsalim"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(rpart)
library(ranger)
library(baguette)
library(bonsai)
library(lightgbm)
library(xgboost)
library(keras)
library(tensorflow)
library(nnet)
library(reticulate)
library(mda)
library(discrim)

tidymodels_prefer()
```

```{r}
train <- read_csv("clean_train.csv")
test <- read_csv("test2.csv")
```

```{r}
factor_conversion <- function(feat) {
  if (n_distinct(feat) <= 20) {
    feat <- as.factor(feat)
  }
  return(feat)
}

train <- train %>%
  mutate(across(everything(), factor_conversion))

test <- test %>%
  mutate(across(everything(), factor_conversion))
```

```{r}
set.seed(2023)
folds <- vfold_cv(data = train, v = 6, strata = action_taken)

rec <- recipe(action_taken ~ ., data = train) %>% 
  step_mutate(state = factor(state)) %>% 
  step_mutate(state = if_else(state == "PR", NA, state)) %>% 
  step_mutate(age_of_applicant_or_borrower = if_else(age_of_applicant_or_borrower %in% c(8888, 9999), NA, age_of_applicant_or_borrower)) %>% 
  step_impute_mean(all_numeric_predictors()) %>% 
  step_impute_mode(all_nominal_predictors()) %>%
  step_cut(loan_term, breaks = c(150, 210, 270, 330, 390), include_outside_range = TRUE) %>% 
  step_YeoJohnson(loan_amount, income, property_value) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>% 
  step_zv(all_predictors()) 

metric <- metric_set(accuracy, roc_auc)
```

```{r}
ctrl_grid <- control_stack_grid()
ctrl_res <- control_stack_resamples()
```

```{r}
# Model Specs

tree_spec <- decision_tree(
    tree_depth = 13,
    cost_complexity = 7.058241e-05,
    min_n = 26
  ) %>%
  set_engine("rpart") %>%
  set_mode("classification")

bagtree_spec <- bag_tree(
    tree_depth = 9,
    min_n = 4,
    cost_complexity = 6.711050e-09
  ) %>%
  set_engine("rpart") %>%
  set_mode("classification")

boosttree_spec <- boost_tree(
    trees = 1257,
    tree_depth = 8, 
    min_n = 11,
    learn_rate = 6.525540e-02
  ) %>%
  set_engine("lightgbm") %>%
  set_mode("classification")

logistic_spec <- logistic_reg(
    penalty = 1.533989e-02, 
    mixture = 0.1048392
  ) %>%
  set_engine("glmnet") %>% 
  set_mode("classification")

lda_spec <- discrim_linear(
    penalty = 3.151749e-01
  ) %>%
    set_engine("mda") %>%
    set_mode("classification")

model_specs <- list(tree_spec, bagtree_spec, boosttree_spec, 
                    logistic_spec, lda_spec)
names(model_specs) <- c("decision_tree", "bagged_trees", "boosted_trees",
                        "logistic_glm", "lda")

```

```{r}
# Workflows

wfls <- list()
for (spec in names(model_specs)) {
  wfl <- workflow() %>% 
    add_model(model_specs[[spec]]) %>% 
    add_recipe(rec)
  
  wfl_name <- paste(c(spec, "_wfl"), collapse = "")
  wfls[[wfl_name]] <- wfl
}
```

```{r}
# Fit Resamples

results <- list()
for (wfl in names(wfls)) {
  res <- wfls[[wfl]] %>% fit_resamples(
    resamples = folds,
    metrics = metric,
    control = ctrl_res
  )
  
  res_name <- paste(c(wfl, "res"), collapse = "")
  results[[res_name]] <- res
}
```

```{r}
results
```

```{r}
# Data Stack

xgboost <- results$xgboost_wflres
lightgbm <- results$lightgbm_wflres
bart <- results$bart_wflres
randforest <- results$randforest_wflres
glmnet <- results$glmnet_wflres
svm_rbf <- results$svmrbf_wflres
svm_lin <- results$svmlin_wflres
cubist <- results$cubist_wflres

data_stack <- stacks() %>% 
  add_candidates(xgboost) %>% 
  add_candidates(lightgbm) %>% 
  add_candidates(bart) %>% 
  add_candidates(randforest) %>% 
  add_candidates(glmnet) %>% 
  add_candidates(svm_rbf) %>% 
  add_candidates(svm_lin) %>% 
  add_candidates(cubist)
```

```{r}
data_stack %>% as_tibble()
```

```{r}
# Model Stack
set.seed(2020)
model_stack <- data_stack %>%
  blend_predictions()

model_stack %>% autoplot()
```

```{r}
model_stack %>% autoplot(type = "members")
```

```{r}
model_stack %>% autoplot(type = "weights")
```

```{r}
# Fitted Stack
set.seed(202)
model_stack <- data_stack %>%
  blend_predictions() %>%
  fit_members()
```

```{r}
collect_parameters(model_stack, "xgboost")
collect_parameters(model_stack, "lightgbm")
collect_parameters(model_stack, "bart")
collect_parameters(model_stack, "randforest")
collect_parameters(model_stack, "glmnet")
collect_parameters(model_stack, "svm_rbf")
collect_parameters(model_stack, "svm_lin")
collect_parameters(model_stack, "cubist")
```

```{r}
pred <- model_stack %>% 
  predict(test)
```

```{r}
pred <- test %>% 
  select(id) %>% 
  bind_cols(pred)
```

```{r}
write_csv(pred, "pred-202-10Folds-Rmd.csv")
```






